// <auto-generated />
using System;
using ErpApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811135204_AddContactsAndCatalog")]
    partial class AddContactsAndCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpApp.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AvailableForSale")
                        .HasColumnType("bit");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HsCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrimaryUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ReOrderLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ValuationMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VatRate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PrimaryUnitId");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.ToTable("Products", "catalog");
                });

            modelBuilder.Entity("ErpApp.Domain.Catalog.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("ProductCategories", "catalog");
                });

            modelBuilder.Entity("ErpApp.Domain.Catalog.ProductSecondaryUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConversionRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("ProductId", "UnitId")
                        .IsUnique();

                    b.ToTable("ProductSecondaryUnits", "catalog");
                });

            modelBuilder.Entity("ErpApp.Domain.Catalog.UnitOfMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("UnitsOfMeasurement", "catalog");
                });

            modelBuilder.Entity("ErpApp.Domain.Configuration.CreditTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DueDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("CreditTerms", "configuration");
                });

            modelBuilder.Entity("ErpApp.Domain.Configuration.CustomFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicableDocumentTypes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("CustomFieldDefinitions", "configuration");
                });

            modelBuilder.Entity("ErpApp.Domain.Configuration.CustomFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("DocumentType", "DocumentId");

                    b.ToTable("CustomFieldValues", "configuration");
                });

            modelBuilder.Entity("ErpApp.Domain.Configuration.CustomStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "DocumentType", "Name")
                        .IsUnique();

                    b.ToTable("CustomStatuses", "configuration");
                });

            modelBuilder.Entity("ErpApp.Domain.Configuration.DocumentNumberingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IncludeFiscalYearInCode")
                        .HasColumnType("bit");

                    b.Property<bool>("LocationWiseNumbering")
                        .HasColumnType("bit");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NextNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ResetEveryFiscalYear")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "DocumentType")
                        .IsUnique();

                    b.ToTable("DocumentNumberingRules", "configuration");
                });

            modelBuilder.Entity("ErpApp.Domain.Configuration.PaymentMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("PaymentModes", "configuration");
                });

            modelBuilder.Entity("ErpApp.Domain.Configuration.ReportingTagCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("ReportingTagCategories", "configuration");
                });

            modelBuilder.Entity("ErpApp.Domain.Configuration.ReportingTagOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrganizationId", "CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("ReportingTagOptions", "configuration");
                });

            modelBuilder.Entity("ErpApp.Domain.Contacts.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pan")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique();

                    b.ToTable("Contacts", "contacts");
                });

            modelBuilder.Entity("ErpApp.Domain.Contacts.ContactGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("ContactGroups", "contacts");
                });

            modelBuilder.Entity("ErpApp.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("ErpApp.Domain.Identity.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Purpose", "CreatedAt");

                    b.ToTable("VerificationCodes", "identity");
                });

            modelBuilder.Entity("ErpApp.Domain.Tenancy.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AccountingStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVatRegistered")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("LockDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PanNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Website")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceName")
                        .IsUnique();

                    b.ToTable("Organizations", "tenancy");
                });

            modelBuilder.Entity("ErpApp.Domain.Tenancy.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "InvitedEmail");

                    b.HasIndex("OrganizationId", "UserId");

                    b.ToTable("OrganizationMemberships", "tenancy");
                });

            modelBuilder.Entity("ErpApp.Domain.Tenancy.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "tenancy");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Description = "Full access to every permission in the Organization.",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Description = "Read-only access; cannot invite users or approve join requests.",
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("ErpApp.Domain.Tenancy.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "PermissionKey")
                        .IsUnique();

                    b.ToTable("RolePermissions", "tenancy");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            IsGranted = true,
                            PermissionKey = "Tenancy.Organization.InviteUser",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            IsGranted = true,
                            PermissionKey = "Tenancy.Organization.AcceptRequest",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            IsGranted = false,
                            PermissionKey = "Tenancy.Organization.InviteUser",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            IsGranted = false,
                            PermissionKey = "Tenancy.Organization.AcceptRequest",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            IsGranted = true,
                            PermissionKey = "Configuration.CreditTerm.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            IsGranted = true,
                            PermissionKey = "Configuration.CreditTerm.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            IsGranted = true,
                            PermissionKey = "Configuration.CreditTerm.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            IsGranted = false,
                            PermissionKey = "Configuration.CreditTerm.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            IsGranted = true,
                            PermissionKey = "Configuration.PaymentMode.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000a"),
                            IsGranted = true,
                            PermissionKey = "Configuration.PaymentMode.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000b"),
                            IsGranted = true,
                            PermissionKey = "Configuration.PaymentMode.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000c"),
                            IsGranted = false,
                            PermissionKey = "Configuration.PaymentMode.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000d"),
                            IsGranted = true,
                            PermissionKey = "Configuration.CustomStatus.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000e"),
                            IsGranted = true,
                            PermissionKey = "Configuration.CustomStatus.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000f"),
                            IsGranted = true,
                            PermissionKey = "Configuration.CustomStatus.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000010"),
                            IsGranted = false,
                            PermissionKey = "Configuration.CustomStatus.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000011"),
                            IsGranted = true,
                            PermissionKey = "Configuration.ReportingTagCategory.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000012"),
                            IsGranted = true,
                            PermissionKey = "Configuration.ReportingTagCategory.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000013"),
                            IsGranted = true,
                            PermissionKey = "Configuration.ReportingTagCategory.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000014"),
                            IsGranted = false,
                            PermissionKey = "Configuration.ReportingTagCategory.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000015"),
                            IsGranted = true,
                            PermissionKey = "Configuration.ReportingTagOption.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000016"),
                            IsGranted = true,
                            PermissionKey = "Configuration.ReportingTagOption.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000017"),
                            IsGranted = true,
                            PermissionKey = "Configuration.ReportingTagOption.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000018"),
                            IsGranted = false,
                            PermissionKey = "Configuration.ReportingTagOption.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000019"),
                            IsGranted = true,
                            PermissionKey = "Configuration.CustomFieldDefinition.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000001a"),
                            IsGranted = true,
                            PermissionKey = "Configuration.CustomFieldDefinition.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000001b"),
                            IsGranted = true,
                            PermissionKey = "Configuration.CustomFieldDefinition.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000001c"),
                            IsGranted = false,
                            PermissionKey = "Configuration.CustomFieldDefinition.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000001d"),
                            IsGranted = true,
                            PermissionKey = "Contacts.ContactGroup.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000001e"),
                            IsGranted = true,
                            PermissionKey = "Contacts.ContactGroup.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000001f"),
                            IsGranted = true,
                            PermissionKey = "Contacts.ContactGroup.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000020"),
                            IsGranted = false,
                            PermissionKey = "Contacts.ContactGroup.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000021"),
                            IsGranted = true,
                            PermissionKey = "Contacts.Contact.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000022"),
                            IsGranted = true,
                            PermissionKey = "Contacts.Contact.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000023"),
                            IsGranted = true,
                            PermissionKey = "Contacts.Contact.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000024"),
                            IsGranted = true,
                            PermissionKey = "Contacts.Contact.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000025"),
                            IsGranted = true,
                            PermissionKey = "Catalog.ProductCategory.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000026"),
                            IsGranted = true,
                            PermissionKey = "Catalog.ProductCategory.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000027"),
                            IsGranted = true,
                            PermissionKey = "Catalog.ProductCategory.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000028"),
                            IsGranted = false,
                            PermissionKey = "Catalog.ProductCategory.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000029"),
                            IsGranted = true,
                            PermissionKey = "Catalog.UnitOfMeasurement.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000002a"),
                            IsGranted = true,
                            PermissionKey = "Catalog.UnitOfMeasurement.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000002b"),
                            IsGranted = true,
                            PermissionKey = "Catalog.UnitOfMeasurement.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000002c"),
                            IsGranted = false,
                            PermissionKey = "Catalog.UnitOfMeasurement.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000002d"),
                            IsGranted = true,
                            PermissionKey = "Catalog.Product.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000002e"),
                            IsGranted = true,
                            PermissionKey = "Catalog.Product.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000002f"),
                            IsGranted = true,
                            PermissionKey = "Catalog.Product.View",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000030"),
                            IsGranted = true,
                            PermissionKey = "Catalog.Product.Manage",
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002")
                        });
                });

            modelBuilder.Entity("ErpApp.Domain.Tenancy.TenantSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InventoryTrackingMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("AccountingMovement");

                    b.Property<string>("NegativeCashBalanceAction")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Reject");

                    b.Property<string>("NegativeStockBalanceAction")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Warn");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductPriceBasis")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ExclusiveOfVat");

                    b.Property<string>("SuggestSellingPriceMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("RecentSellingPrice");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("TenantSettings", "tenancy");
                });

            modelBuilder.Entity("ErpApp.Domain.Tenancy.TenantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IrdSyncEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("ManufacturingEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("MultiCurrencyEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("MultipleLocationsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("MultipleWarehousesEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PosRestaurantEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("PosRetailEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("TrackInventoryEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("TrialEndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TrialStartsAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("TenantSubscriptions", "tenancy");
                });

            modelBuilder.Entity("ErpApp.Domain.Catalog.Product", b =>
                {
                    b.HasOne("ErpApp.Domain.Catalog.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpApp.Domain.Catalog.UnitOfMeasurement", null)
                        .WithMany()
                        .HasForeignKey("PrimaryUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ErpApp.Domain.Catalog.ProductCategory", b =>
                {
                    b.HasOne("ErpApp.Domain.Catalog.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ErpApp.Domain.Catalog.ProductSecondaryUnit", b =>
                {
                    b.HasOne("ErpApp.Domain.Catalog.Product", null)
                        .WithMany("SecondaryUnits")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpApp.Domain.Catalog.UnitOfMeasurement", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ErpApp.Domain.Configuration.CustomFieldValue", b =>
                {
                    b.HasOne("ErpApp.Domain.Configuration.CustomFieldDefinition", null)
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErpApp.Domain.Configuration.ReportingTagOption", b =>
                {
                    b.HasOne("ErpApp.Domain.Configuration.ReportingTagCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ErpApp.Domain.Contacts.Contact", b =>
                {
                    b.HasOne("ErpApp.Domain.Contacts.ContactGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ErpApp.Domain.Contacts.ContactGroup", b =>
                {
                    b.HasOne("ErpApp.Domain.Contacts.ContactGroup", null)
                        .WithMany()
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ErpApp.Domain.Identity.VerificationCode", b =>
                {
                    b.HasOne("ErpApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErpApp.Domain.Tenancy.OrganizationMembership", b =>
                {
                    b.HasOne("ErpApp.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpApp.Domain.Tenancy.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpApp.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ErpApp.Domain.Tenancy.RolePermission", b =>
                {
                    b.HasOne("ErpApp.Domain.Tenancy.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErpApp.Domain.Tenancy.TenantSettings", b =>
                {
                    b.HasOne("ErpApp.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErpApp.Domain.Tenancy.TenantSubscription", b =>
                {
                    b.HasOne("ErpApp.Domain.Tenancy.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErpApp.Domain.Catalog.Product", b =>
                {
                    b.Navigation("SecondaryUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
